### ISSUE TITLE
Cipher s

### ISSUE THREAD

**Issue by Retrovers** [jerome-amp/Youtube-Downloader#2]
Hi, 
Cipher decryption is not worlking

**Comment by jerome-amp** [comment]
Hi,

You're right, the JS encryption function can be called with alphanumeric characters, not only in alpha. I corrected this as well as the presence of a useless \n in another mask.

Can you confirm to me that the code is again functional on protected videos ?

Thank you for your feedback

**Comment by Retrovers** [comment]
Yes your code functional on vevo videos !
Great job

**Comment by jerome-amp** [comment]
Perfect, have fun !

**Comment by mattafixes** [comment]
Hi,
Now, i have checked this, not working for vevo videos.
Could you check again?
Thanks

**Comment by jerome-amp** [comment]
Hi, Indeed Youtube change the JS URL definition, It's no more relative.
I corrected this problem, thank you for noticing it !
