### ISSUE TITLE
It loading too much time and return error

### ISSUE THREAD

**Issue by manivannan909** [jerome-amp/Youtube-Downloader#3]
It take too much time to load or failure as time out

**Comment by jerome-amp** [comment]
With witch video ID did you try ? it still works on me :

http://s597900825.onlinehome.fr/yt.php

**Comment by manivannan909** [comment]
s with video id

**Comment by jerome-amp** [comment]
What is you video ID /?v=XXXXXXXX

**Comment by manivannan909** [comment]
34Na4j8AVgA

**Comment by manivannan909** [comment]
my coding is 



 <form  method="get"  action="video.php"><br>
		<h1>Youtube Downloader</h1><br><br><br>
		<input type="text" name="videoid" id="videoid"  placeholder="Example:-http://www.youtube.com/watch?v=Fw-BM-Mqgeg" />
		<input class="btn btn-primary" type="submit" name="type" id="type" value="Download" />
		
        </form><br>

then 
if(isset($_REQUEST['videoid'])) {
	$my_id = $_REQUEST['videoid'];
	if( preg_match('/^https:\/\/w{3}?.youtube.com\//', $my_id) ){
		$url   = parse_url($my_id);
		$my_id = NULL;
		if( is_array($url) && count($url)>0 && isset($url['query']) && !empty($url['query']) ){
			$parts = explode('&',$url['query']);
			if( is_array($parts) && count($parts) > 0 ){
				foreach( $parts as $p ){
					$pattern = '/^v\=/';
					if( preg_match($pattern, $p) ){
						$my_id = preg_replace($pattern,'',$p);
						break;
					}
				}
			}
			if( !$my_id ){
				echo '<p>No video id passed in</p>';
				exit;
			}
		}else{
			echo '<p>Invalid url</p>';
			exit;
		}
	}elseif( preg_match('/^https?:\/\/youtu.be/', $my_id) ) {
		$url   = parse_url($my_id);
		$my_id = NULL;
		$my_id = preg_replace('/^\//', '', $url['path']);
	}
} else {
	echo '<p>No video id passed in</p>';
	exit;
}

then
<?php
					$v = isset($_GET['v']) ? $_GET['v'] : $my_id;
					
					$youtube = new youtube($v);

**Comment by jerome-amp** [comment]
Upload the code dans send me the link, It's works with the same source code than you can download here : 
http://s597900825.onlinehome.fr/yt.php?v=34Na4j8AVgA

**Comment by manivannan909** [comment]
it working in ur website. i had doubt . i need to change $v="" code in youtube .php

**Comment by jerome-amp** [comment]
I think you don't have to modifiy youtube.php it works like that.

Echo your $v just before you give it to the youtube class and check if it's the expected value.

**Comment by manivannan909** [comment]
ty. Can i use Your coding in live website?

**Comment by jerome-amp** [comment]
I delete the live souce ;) but i just host these too files that you can download on this github :

- index.php
- youtube.php

**Comment by manivannan909** [comment]
it is possible i can get live source code?

**Comment by jerome-amp** [comment]
It's on this github ^^

https://github.com/jerome-amp/Youtube-Downloader/blob/master/index.php
