### ISSUE TITLE
This link not working can u help me

### ISSUE THREAD

**Issue by manivannan909** [jerome-amp/Youtube-Downloader#4]
can u check and solve the problem
v=d2ibxAISMVQ

**Comment by jerome-amp** [comment]
From my side it still works : http://s597900825.onlinehome.fr/yt.php?v=d2ibxAISMVQ

**Comment by manivannan909** [comment]
see this website it not working http://onlineutubedownloader.com/video.php?v=d2ibxAISMVQ

**Comment by manivannan909** [comment]
sir it is possible to change code as curl?

**Comment by manivannan909** [comment]
error 
Undefined index: vid in /storage/h3/106/599106/public_html/youtube.php on line 24

**Comment by jerome-amp** [comment]
Echo the $contents line 18 and check if you can found "ytplayer.config = {..."

**Comment by manivannan909** [comment]
sir another error is ur unauthorized to download video

**Comment by manivannan909** [comment]
ytplayer.config is not avaible in $contents for that vevo video

**Comment by jerome-amp** [comment]
The problem probably comes from the country of origin of the request, try to go through a proxy or a VPN to execute this same request from another country.

**Comment by manivannan909** [comment]
sir localhost it working fine .

**Comment by manivannan909** [comment]
problem only at vevo video

**Comment by manivannan909** [comment]
which country this link http://s597900825.onlinehome.fr/yt.php?v=d2ibxAISMVQ ?

**Comment by jerome-amp** [comment]
This server is in Germany.

**Comment by manivannan909** [comment]
sir what is idea for this problem. 

You have contact in fb or anything else

**Comment by manivannan909** [comment]
it is possible i can create that server  one account in that server

**Comment by jerome-amp** [comment]
Put this on your server and give me the link of the file : 

echo file_get_contents('https://www.youtube.com/watch?v=d2ibxAISMVQ', false, stream_context_create(array('ssl' => array('verify_peer' => false))));

**Comment by manivannan909** [comment]
k

**Comment by manivannan909** [comment]
video not loading

**Comment by manivannan909** [comment]
https://onlineutubedownloader.000webhostapp.com/video.php

**Comment by jerome-amp** [comment]
It should work, can you upload, the two files unmodified of this github, index.php and youtube.php on your server, and give me the link of the index file.

**Comment by manivannan909** [comment]
k

**Comment by manivannan909** [comment]
https://youtubetest.000webhostapp.com/

**Comment by jerome-amp** [comment]
With this files : 
https://github.com/jerome-amp/Youtube-Downloader/blob/master/index.php
https://github.com/jerome-amp/Youtube-Downloader/blob/master/youtube.php

**Comment by manivannan909** [comment]
s sir.

**Comment by manivannan909** [comment]
only changes  echo file_get_contents('https://www.youtube.com/watch?v=d2ibxAISMVQ', false, stream_context_create(array('ssl' => array('verify_peer' => false))));

**Comment by manivannan909** [comment]
The uploader has not made this video available in your country.

**Comment by jerome-amp** [comment]
Yes that's the problem i told you before, you have to change the country for some videos.

**Comment by manivannan909** [comment]
i think your country server working fine

**Comment by manivannan909** [comment]
can u give idea for proxy

**Comment by manivannan909** [comment]
idk how it is not working. actually video belong to my country

**Comment by manivannan909** [comment]
sir your link is permanent link ?

**Comment by jerome-amp** [comment]
No it's not, sorry but i have to close this issue, because the code isn't concerned.

**Comment by manivannan909** [comment]
k sir

**Comment by manivannan909** [comment]
sir your link is permanent link ?

**Comment by manivannan909** [comment]
thank you very much for kind help and i cant start new issue

**Comment by jerome-amp** [comment]
Your welcome, good luck for the rest of your project.
