### ISSUE TITLE
serious issue not downloading

### ISSUE THREAD

**Issue by jhaylee2016** [jerome-amp/Youtube-Downloader#6]
hey sir good day,,,i just find out that this script works only on localhost or xampp or local server,,,but when i uploaded on web hosting online...I already tested on hostgator and ipage hosting but it fails to download I will get the 

You don't have authorization to view this page.
HTTP ERROR 403

how to fix this sir...

**Comment by jerome-amp** [comment]
Hi, i'm sorry but it can't be an issue of the script if the script works.
You should see this problem with your host ( PHP version, allow_url_fopen... )

**Comment by jhaylee2016** [comment]
Ohh....my host is hostgator and bluehost...do you mean thats the problem...for me no the problem is your script sir...because the generated url is the problem its 403 denied is there a connection of 403 between the host..hehehe..

**Comment by jhaylee2016** [comment]
So dont close this issue sir its not yet fix...tou should attach some demo of yours using your hosting...
